// AUTO-GENERATED from the Supabase project's PostgREST schema.
// Shape mirrors `supabase gen types typescript`. Row nullability is
// derived from NOT NULL info; Insert/Update are permissive. Regenerate
// with `supabase gen types typescript --linked > types/database.ts`
// once the Supabase CLI is linked.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      addons: {
        Row: {
          id: string;
          name: string;
          slug: string;
          short_description: string | null;
          description: string | null;
          price_cents: number;
          currency: string;
          interval: Database["public"]["Enums"]["billing_interval"];
          duration_days: number | null;
          stripe_product_id: string | null;
          stripe_price_id: string | null;
          effect: string;
          effect_value: number;
          max_quantity: number;
          package_ids: string[];
          fulfilment_note: string | null;
          badge_label: string | null;
          image_url: string | null;
          is_active: boolean;
          is_public: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name?: string;
          slug?: string;
          short_description?: string | null;
          description?: string | null;
          price_cents?: number;
          currency?: string;
          interval?: Database["public"]["Enums"]["billing_interval"];
          duration_days?: number | null;
          stripe_product_id?: string | null;
          stripe_price_id?: string | null;
          effect?: string;
          effect_value?: number;
          max_quantity?: number;
          package_ids?: string[];
          fulfilment_note?: string | null;
          badge_label?: string | null;
          image_url?: string | null;
          is_active?: boolean;
          is_public?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          short_description?: string | null;
          description?: string | null;
          price_cents?: number;
          currency?: string;
          interval?: Database["public"]["Enums"]["billing_interval"];
          duration_days?: number | null;
          stripe_product_id?: string | null;
          stripe_price_id?: string | null;
          effect?: string;
          effect_value?: number;
          max_quantity?: number;
          package_ids?: string[];
          fulfilment_note?: string | null;
          badge_label?: string | null;
          image_url?: string | null;
          is_active?: boolean;
          is_public?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      asset_deletion_queue: {
        Row: {
          id: number;
          bucket_id: string;
          object_path: string;
          reason: string | null;
          listing_id: string | null;
          status: string;
          attempts: number;
          last_error: string | null;
          created_at: string;
          processed_at: string | null;
        };
        Insert: {
          id?: number;
          bucket_id?: string;
          object_path?: string;
          reason?: string | null;
          listing_id?: string | null;
          status?: string;
          attempts?: number;
          last_error?: string | null;
          created_at?: string;
          processed_at?: string | null;
        };
        Update: {
          id?: number;
          bucket_id?: string;
          object_path?: string;
          reason?: string | null;
          listing_id?: string | null;
          status?: string;
          attempts?: number;
          last_error?: string | null;
          created_at?: string;
          processed_at?: string | null;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: number;
          actor_id: string | null;
          actor_email: string | null;
          action: string;
          entity_type: string | null;
          entity_id: string | null;
          diff: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          actor_id?: string | null;
          actor_email?: string | null;
          action?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          diff?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          actor_id?: string | null;
          actor_email?: string | null;
          action?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          diff?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          icon: string | null;
          ages_label: string;
          rate_label: string;
          sort_order: number;
          is_active: boolean;
          listing_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          icon?: string | null;
          ages_label?: string;
          rate_label?: string;
          sort_order?: number;
          is_active?: boolean;
          listing_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          icon?: string | null;
          ages_label?: string;
          rate_label?: string;
          sort_order?: number;
          is_active?: boolean;
          listing_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      email_log: {
        Row: {
          id: number;
          template_key: string | null;
          to_email: string;
          subject: string | null;
          listing_id: string | null;
          user_id: string | null;
          status: string;
          provider_id: string | null;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          template_key?: string | null;
          to_email?: string;
          subject?: string | null;
          listing_id?: string | null;
          user_id?: string | null;
          status?: string;
          provider_id?: string | null;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          template_key?: string | null;
          to_email?: string;
          subject?: string | null;
          listing_id?: string | null;
          user_id?: string | null;
          status?: string;
          provider_id?: string | null;
          error_message?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      email_template_versions: {
        Row: {
          id: number;
          template_key: string;
          version: number;
          snapshot: Json;
          changed_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          template_key?: string;
          version?: number;
          snapshot?: Json;
          changed_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          template_key?: string;
          version?: number;
          snapshot?: Json;
          changed_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      email_templates: {
        Row: {
          key: string;
          name: string;
          description: string | null;
          category: string;
          audience: string;
          subject: string;
          preheader: string | null;
          heading: string;
          body: string;
          callout: string | null;
          cta_label: string | null;
          cta_path: string | null;
          footer_note: string | null;
          variables: Json;
          is_enabled: boolean;
          is_locked: boolean;
          version: number;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          key?: string;
          name?: string;
          description?: string | null;
          category?: string;
          audience?: string;
          subject?: string;
          preheader?: string | null;
          heading?: string;
          body?: string;
          callout?: string | null;
          cta_label?: string | null;
          cta_path?: string | null;
          footer_note?: string | null;
          variables?: Json;
          is_enabled?: boolean;
          is_locked?: boolean;
          version?: number;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          key?: string;
          name?: string;
          description?: string | null;
          category?: string;
          audience?: string;
          subject?: string;
          preheader?: string | null;
          heading?: string;
          body?: string;
          callout?: string | null;
          cta_label?: string | null;
          cta_path?: string | null;
          footer_note?: string | null;
          variables?: Json;
          is_enabled?: boolean;
          is_locked?: boolean;
          version?: number;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      form_fields: {
        Row: {
          id: string;
          section_id: string | null;
          category_id: string | null;
          key: string;
          label: string;
          help_text: string | null;
          placeholder: string | null;
          field_type: string;
          options: Json;
          is_required: boolean;
          is_core: boolean;
          column_name: string | null;
          show_on_public: boolean;
          max_length: number | null;
          strength_points: number;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          section_id?: string | null;
          category_id?: string | null;
          key?: string;
          label?: string;
          help_text?: string | null;
          placeholder?: string | null;
          field_type?: string;
          options?: Json;
          is_required?: boolean;
          is_core?: boolean;
          column_name?: string | null;
          show_on_public?: boolean;
          max_length?: number | null;
          strength_points?: number;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          section_id?: string | null;
          category_id?: string | null;
          key?: string;
          label?: string;
          help_text?: string | null;
          placeholder?: string | null;
          field_type?: string;
          options?: Json;
          is_required?: boolean;
          is_core?: boolean;
          column_name?: string | null;
          show_on_public?: boolean;
          max_length?: number | null;
          strength_points?: number;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      form_sections: {
        Row: {
          id: string;
          key: string;
          title: string;
          subtitle: string | null;
          sort_order: number;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          key?: string;
          title?: string;
          subtitle?: string | null;
          sort_order?: number;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          key?: string;
          title?: string;
          subtitle?: string | null;
          sort_order?: number;
          is_active?: boolean;
        };
        Relationships: [];
      };
      inquiries: {
        Row: {
          id: string;
          listing_id: string;
          name: string;
          email: string;
          phone: string | null;
          message: string;
          status: string;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          listing_id?: string;
          name?: string;
          email?: string;
          phone?: string | null;
          message?: string;
          status?: string;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          listing_id?: string;
          name?: string;
          email?: string;
          phone?: string | null;
          message?: string;
          status?: string;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      integration_settings: {
        Row: {
          provider: string;
          label: string;
          public_config: Json;
          secret_ciphertext: string | null;
          secret_hint: string | null;
          secret_updated_at: string | null;
          secret_updated_by: string | null;
          is_enabled: boolean;
          last_success_at: string | null;
          last_error_at: string | null;
          last_error_message: string | null;
          updated_at: string;
        };
        Insert: {
          provider?: string;
          label?: string;
          public_config?: Json;
          secret_ciphertext?: string | null;
          secret_hint?: string | null;
          secret_updated_at?: string | null;
          secret_updated_by?: string | null;
          is_enabled?: boolean;
          last_success_at?: string | null;
          last_error_at?: string | null;
          last_error_message?: string | null;
          updated_at?: string;
        };
        Update: {
          provider?: string;
          label?: string;
          public_config?: Json;
          secret_ciphertext?: string | null;
          secret_hint?: string | null;
          secret_updated_at?: string | null;
          secret_updated_by?: string | null;
          is_enabled?: boolean;
          last_success_at?: string | null;
          last_error_at?: string | null;
          last_error_message?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      listing_addons: {
        Row: {
          id: string;
          listing_id: string;
          addon_id: string;
          owner_id: string;
          quantity: number;
          status: string;
          amount_cents: number;
          stripe_checkout_id: string | null;
          stripe_invoice_id: string | null;
          stripe_subscription_item_id: string | null;
          payment_id: string | null;
          starts_at: string | null;
          expires_at: string | null;
          fulfilled_at: string | null;
          fulfilled_by: string | null;
          fulfilment_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          listing_id?: string;
          addon_id?: string;
          owner_id?: string;
          quantity?: number;
          status?: string;
          amount_cents?: number;
          stripe_checkout_id?: string | null;
          stripe_invoice_id?: string | null;
          stripe_subscription_item_id?: string | null;
          payment_id?: string | null;
          starts_at?: string | null;
          expires_at?: string | null;
          fulfilled_at?: string | null;
          fulfilled_by?: string | null;
          fulfilment_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          listing_id?: string;
          addon_id?: string;
          owner_id?: string;
          quantity?: number;
          status?: string;
          amount_cents?: number;
          stripe_checkout_id?: string | null;
          stripe_invoice_id?: string | null;
          stripe_subscription_item_id?: string | null;
          payment_id?: string | null;
          starts_at?: string | null;
          expires_at?: string | null;
          fulfilled_at?: string | null;
          fulfilled_by?: string | null;
          fulfilment_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      listing_images: {
        Row: {
          id: string;
          listing_id: string;
          storage_path: string;
          thumb_path: string | null;
          alt_text: string | null;
          width: number | null;
          height: number | null;
          bytes: number | null;
          sort_order: number;
          is_cover: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          listing_id?: string;
          storage_path?: string;
          thumb_path?: string | null;
          alt_text?: string | null;
          width?: number | null;
          height?: number | null;
          bytes?: number | null;
          sort_order?: number;
          is_cover?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          listing_id?: string;
          storage_path?: string;
          thumb_path?: string | null;
          alt_text?: string | null;
          width?: number | null;
          height?: number | null;
          bytes?: number | null;
          sort_order?: number;
          is_cover?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      listing_tags: {
        Row: {
          listing_id: string;
          tag_id: string;
        };
        Insert: {
          listing_id?: string;
          tag_id?: string;
        };
        Update: {
          listing_id?: string;
          tag_id?: string;
        };
        Relationships: [];
      };
      listings: {
        Row: {
          id: string;
          owner_id: string;
          category_id: string;
          package_id: string | null;
          status: Database["public"]["Enums"]["listing_status"];
          slug: string | null;
          business_name: string;
          contact_name: string | null;
          contact_email: string | null;
          contact_phone: string | null;
          show_phone: boolean;
          website: string | null;
          description: string | null;
          description_html: string | null;
          social: Json;
          address_line: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          country: string | null;
          also_serves: string[];
          latitude: number | null;
          longitude: number | null;
          google_place_id: string | null;
          ages_served: string | null;
          rate_text: string | null;
          accepts_esa: Database["public"]["Enums"]["esa_answer"] | null;
          custom_fields: Json;
          is_featured: boolean;
          featured_until: string | null;
          priority_rank: number;
          completeness: number;
          view_count: number;
          inquiry_count: number;
          submitted_at: string | null;
          published_at: string | null;
          reviewed_at: string | null;
          reviewed_by: string | null;
          rejection_reason: string | null;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          search_vector: string | null;
        };
        Insert: {
          id?: string;
          owner_id?: string;
          category_id?: string;
          package_id?: string | null;
          status?: Database["public"]["Enums"]["listing_status"];
          slug?: string | null;
          business_name?: string;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          show_phone?: boolean;
          website?: string | null;
          description?: string | null;
          description_html?: string | null;
          social?: Json;
          address_line?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string | null;
          also_serves?: string[];
          latitude?: number | null;
          longitude?: number | null;
          google_place_id?: string | null;
          ages_served?: string | null;
          rate_text?: string | null;
          accepts_esa?: Database["public"]["Enums"]["esa_answer"] | null;
          custom_fields?: Json;
          is_featured?: boolean;
          featured_until?: string | null;
          priority_rank?: number;
          completeness?: number;
          view_count?: number;
          inquiry_count?: number;
          submitted_at?: string | null;
          published_at?: string | null;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          rejection_reason?: string | null;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          search_vector?: string | null;
        };
        Update: {
          id?: string;
          owner_id?: string;
          category_id?: string;
          package_id?: string | null;
          status?: Database["public"]["Enums"]["listing_status"];
          slug?: string | null;
          business_name?: string;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          show_phone?: boolean;
          website?: string | null;
          description?: string | null;
          description_html?: string | null;
          social?: Json;
          address_line?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string | null;
          also_serves?: string[];
          latitude?: number | null;
          longitude?: number | null;
          google_place_id?: string | null;
          ages_served?: string | null;
          rate_text?: string | null;
          accepts_esa?: Database["public"]["Enums"]["esa_answer"] | null;
          custom_fields?: Json;
          is_featured?: boolean;
          featured_until?: string | null;
          priority_rank?: number;
          completeness?: number;
          view_count?: number;
          inquiry_count?: number;
          submitted_at?: string | null;
          published_at?: string | null;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          rejection_reason?: string | null;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          search_vector?: string | null;
        };
        Relationships: [];
      };
      menu_items: {
        Row: {
          id: string;
          location: string;
          parent_id: string | null;
          label: string;
          url: string;
          opens_new_tab: boolean;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          location?: string;
          parent_id?: string | null;
          label?: string;
          url?: string;
          opens_new_tab?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          location?: string;
          parent_id?: string | null;
          label?: string;
          url?: string;
          opens_new_tab?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      packages: {
        Row: {
          id: string;
          name: string;
          slug: string;
          tagline: string | null;
          description: string | null;
          price_cents: number;
          currency: string;
          interval: Database["public"]["Enums"]["billing_interval"];
          trial_days: number;
          stripe_product_id: string | null;
          stripe_price_id: string | null;
          min_listings: number;
          max_listings: number | null;
          max_images: number;
          requires_approval: boolean;
          allows_featured: boolean;
          priority_rank: number;
          badge_label: string | null;
          badge_color: string | null;
          features: Json;
          is_default: boolean;
          is_active: boolean;
          is_public: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name?: string;
          slug?: string;
          tagline?: string | null;
          description?: string | null;
          price_cents?: number;
          currency?: string;
          interval?: Database["public"]["Enums"]["billing_interval"];
          trial_days?: number;
          stripe_product_id?: string | null;
          stripe_price_id?: string | null;
          min_listings?: number;
          max_listings?: number | null;
          max_images?: number;
          requires_approval?: boolean;
          allows_featured?: boolean;
          priority_rank?: number;
          badge_label?: string | null;
          badge_color?: string | null;
          features?: Json;
          is_default?: boolean;
          is_active?: boolean;
          is_public?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          tagline?: string | null;
          description?: string | null;
          price_cents?: number;
          currency?: string;
          interval?: Database["public"]["Enums"]["billing_interval"];
          trial_days?: number;
          stripe_product_id?: string | null;
          stripe_price_id?: string | null;
          min_listings?: number;
          max_listings?: number | null;
          max_images?: number;
          requires_approval?: boolean;
          allows_featured?: boolean;
          priority_rank?: number;
          badge_label?: string | null;
          badge_color?: string | null;
          features?: Json;
          is_default?: boolean;
          is_active?: boolean;
          is_public?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          user_id: string | null;
          listing_id: string | null;
          subscription_id: string | null;
          stripe_payment_intent_id: string | null;
          stripe_invoice_id: string | null;
          stripe_checkout_id: string | null;
          amount_cents: number;
          currency: string;
          status: string;
          description: string | null;
          receipt_url: string | null;
          paid_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          listing_id?: string | null;
          subscription_id?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_invoice_id?: string | null;
          stripe_checkout_id?: string | null;
          amount_cents?: number;
          currency?: string;
          status?: string;
          description?: string | null;
          receipt_url?: string | null;
          paid_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          listing_id?: string | null;
          subscription_id?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_invoice_id?: string | null;
          stripe_checkout_id?: string | null;
          amount_cents?: number;
          currency?: string;
          status?: string;
          description?: string | null;
          receipt_url?: string | null;
          paid_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          phone: string | null;
          role: Database["public"]["Enums"]["user_role"];
          is_verified: boolean;
          is_suspended: boolean;
          onboarding_complete: boolean;
          stripe_customer_id: string | null;
          avatar_url: string | null;
          business_address: string | null;
          notes: string | null;
          last_seen_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email?: string;
          full_name?: string | null;
          phone?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          is_verified?: boolean;
          is_suspended?: boolean;
          onboarding_complete?: boolean;
          stripe_customer_id?: string | null;
          avatar_url?: string | null;
          business_address?: string | null;
          notes?: string | null;
          last_seen_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          phone?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          is_verified?: boolean;
          is_suspended?: boolean;
          onboarding_complete?: boolean;
          stripe_customer_id?: string | null;
          avatar_url?: string | null;
          business_address?: string | null;
          notes?: string | null;
          last_seen_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      rate_limits: {
        Row: {
          bucket: string;
          window_start: string;
          hits: number;
        };
        Insert: {
          bucket?: string;
          window_start?: string;
          hits?: number;
        };
        Update: {
          bucket?: string;
          window_start?: string;
          hits?: number;
        };
        Relationships: [];
      };
      site_scripts: {
        Row: {
          id: string;
          name: string;
          kind: string;
          config: Json;
          code: string | null;
          placement: string;
          applies_to: string;
          external_hosts: string[];
          consent_group: string;
          is_active: boolean;
          sort_order: number;
          notes: string | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name?: string;
          kind?: string;
          config?: Json;
          code?: string | null;
          placement?: string;
          applies_to?: string;
          external_hosts?: string[];
          consent_group?: string;
          is_active?: boolean;
          sort_order?: number;
          notes?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          kind?: string;
          config?: Json;
          code?: string | null;
          placement?: string;
          applies_to?: string;
          external_hosts?: string[];
          consent_group?: string;
          is_active?: boolean;
          sort_order?: number;
          notes?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      site_settings: {
        Row: {
          key: string;
          value: Json;
          label: string | null;
          group_name: string | null;
          is_public: boolean;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          key?: string;
          value?: Json;
          label?: string | null;
          group_name?: string | null;
          is_public?: boolean;
          updated_at?: string;
          updated_by?: string | null;
        };
        Update: {
          key?: string;
          value?: Json;
          label?: string | null;
          group_name?: string | null;
          is_public?: boolean;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      stripe_events: {
        Row: {
          id: string;
          type: string;
          payload: Json | null;
          processed_at: string;
        };
        Insert: {
          id?: string;
          type?: string;
          payload?: Json | null;
          processed_at?: string;
        };
        Update: {
          id?: string;
          type?: string;
          payload?: Json | null;
          processed_at?: string;
        };
        Relationships: [];
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          package_id: string | null;
          listing_id: string | null;
          stripe_subscription_id: string | null;
          stripe_customer_id: string | null;
          status: Database["public"]["Enums"]["subscription_status"];
          current_period_start: string | null;
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          canceled_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          package_id?: string | null;
          listing_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_customer_id?: string | null;
          status?: Database["public"]["Enums"]["subscription_status"];
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          canceled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          package_id?: string | null;
          listing_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_customer_id?: string | null;
          status?: Database["public"]["Enums"]["subscription_status"];
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          canceled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tag_groups: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          category_id: string | null;
          selection_type: string;
          show_in_form: boolean;
          show_in_filter: boolean;
          show_on_listing: boolean;
          sort_mode: string;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          category_id?: string | null;
          selection_type?: string;
          show_in_form?: boolean;
          show_in_filter?: boolean;
          show_on_listing?: boolean;
          sort_mode?: string;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          category_id?: string | null;
          selection_type?: string;
          show_in_form?: boolean;
          show_in_filter?: boolean;
          show_on_listing?: boolean;
          sort_mode?: string;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tags: {
        Row: {
          id: string;
          group_id: string;
          name: string;
          slug: string;
          description: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          group_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          group_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      increment_listing_view: {
        Args: { p_listing_id: string };
        Returns: undefined;
      };
      create_inquiry: {
        Args: {
          p_listing_id: string;
          p_name: string;
          p_email: string;
          p_message: string;
          p_phone?: string | null;
          p_ip?: string | null;
          p_user_agent?: string | null;
        };
        Returns: string;
      };
      listing_entitlements: {
        Args: { p_listing_id: string };
        Returns: {
          featured: boolean;
          max_images: number;
          video_embed: boolean;
          max_listings: number;
          homepage_slot: boolean;
          priority_rank: number;
          inquiry_alerts: boolean;
          verified_badge: boolean;
        };
      };
      hit_rate_limit: {
        Args: {
          p_bucket: string;
          p_limit: number;
          p_window_seconds: number;
        };
        Returns: {
          allowed: boolean;
          remaining: number;
          reset_at: string;
        }[];
      };
      search_listings: {
        Args: {
          p_query?: string;
          p_category?: string;
          p_city?: string;
          p_tag_slugs?: string[];
          p_esa?: string;
          p_bbox?: number[];
          p_limit?: number;
          p_offset?: number;
        };
        Returns: {
          id: string;
          slug: string;
          business_name: string;
          city: string | null;
          state: string | null;
          latitude: number | null;
          longitude: number | null;
          category_name: string | null;
          category_slug: string | null;
          cover_path: string | null;
          is_featured: boolean;
          completeness: number | null;
          total_count: number;
        }[];
      };
    };
    Enums: {
      billing_interval: "one_time" | "month" | "year";
      esa_answer: "yes" | "no" | "unsure";
      listing_status: "draft" | "pending_review" | "published" | "rejected" | "unpublished" | "archived";
      subscription_status: "incomplete" | "trialing" | "active" | "past_due" | "canceled" | "unpaid" | "paused";
      user_role: "user" | "moderator" | "admin";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
